@extends('layouts.app')
@section('content')
<div class="flex flex-col gap-6">
    <div class="flex flex-wrap items-center justify-between gap-4"><div>
        <a href="{{ route('admin.stores.index') }}" class="text-sm font-semibold text-emerald-700">← Stores</a>
        <h1 class="mt-2 text-3xl font-bold text-gray-900">{{ $store->name }}</h1><p class="mt-1 text-sm text-gray-500">{{ $store->address }}</p>
    </div><a href="{{ route('admin.stores.products.create', $store) }}" class="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white">+ Add product</a></div>
@if(session('success'))<div class="rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}
</div>@endif
<div class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Product</th><th class="px-5 py-3">Category</th><th class="px-5 py-3">Price</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($products as $product)<tr><td class="flex items-center gap-3 px-5 py-3"><div class="h-12 w-12 overflow-hidden rounded-lg bg-gray-100">@if($product->image_path)<img src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->product_name }}" class="h-full w-full object-cover">@endif</div><span class="font-semibold text-gray-900">{{ $product->product_name }}</span></td><td class="px-5 py-3 text-gray-500">{{ $product->category }}</td><td class="px-5 py-3 font-semibold">Rp {{ number_format($product->price, 0, ',', '.') }}</td><td class="px-5 py-3"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $product->is_available ? 'bg-emerald-50 text-emerald-700' : 'bg-gray-100 text-gray-500' }}">{{ $product->is_available ? 'Available' : 'Hidden' }}</span></td><td class="px-5 py-3 text-right"><a href="{{ route('admin.stores.products.edit', [$store, $product]) }}" class="mr-3 text-xs font-semibold text-emerald-700">Edit</a><form class="inline" method="POST" action="{{ route('admin.stores.products.destroy', [$store, $product]) }}" onsubmit="return confirm('Delete this product?')">@csrf @method('DELETE')<button class="text-xs font-semibold text-red-600">Delete</button></form></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-sm text-gray-500">No products in this store yet.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection