@extends('layouts.app')
@section('content')
<div class="mx-auto max-w-5xl space-y-6"><div><p class="text-sm font-semibold text-emerald-700">MEALWISE / MEMBERSHIP</p><h1 class="mt-1 text-3xl font-bold text-gray-900">Weekly membership</h1><p class="mt-1 text-sm text-gray-500">Unlock flexible date-range meal plans after admin verifies your payment.</p></div>
@if(session('success'))<div class="rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif @if(session('error'))<div class="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{{ session('error') }}</div>@endif
<div class="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section class="rounded-2xl bg-emerald-900 p-7 text-white"><p class="text-xs font-bold uppercase tracking-widest text-lime-300">WEEKLY PLAN</p><h2 class="mt-5 text-3xl font-bold">7 days of better meals.</h2><p class="mt-3 text-sm leading-6 text-emerald-100">One shopping list, daily recipes, and calorie guidance for the whole week.</p><p class="mt-8 text-3xl font-bold">Rp {{ number_format($price, 0, ',', '.') }} <span class="text-sm font-normal text-emerald-200">/ week</span></p><div class="mt-7 space-y-3 text-sm text-emerald-100"><p>✓ 7-day meal plan</p><p>✓ Shopping list by store</p><p>✓ Recipe and calorie details</p></div></section><section class="rounded-2xl border border-gray-200 bg-white p-7 shadow-sm"><h2 class="text-xl font-bold text-gray-900">Choose payment method</h2><form class="mt-6 space-y-5" method="POST" action="{{ route('membership.upgrade') }}" enctype="multipart/form-data">@csrf<div class="grid gap-3 sm:grid-cols-2"><label class="cursor-pointer rounded-xl border border-gray-200 p-4 has-[:checked]:border-emerald-600 has-[:checked]:bg-emerald-50"><input class="mr-2" type="radio" name="method" value="bank_transfer" checked onchange="document.getElementById('bankInfo').hidden=false;document.getElementById('qrisInfo').hidden=true;document.getElementById('proofField').hidden=false">Bank transfer</label><label class="cursor-pointer rounded-xl border border-gray-200 p-4 has-[:checked]:border-emerald-600 has-[:checked]:bg-emerald-50"><input class="mr-2" type="radio" name="method" value="qris" onchange="document.getElementById('bankInfo').hidden=true;document.getElementById('qrisInfo').hidden=false;document.getElementById('proofField').hidden=true">QRIS</label></div><div id="bankInfo" class="rounded-xl bg-gray-50 p-4 text-sm"><p class="font-semibold text-gray-900">Transfer ke</p><p class="mt-1 text-emerald-700">{{ $bankAccount }}</p><p class="mt-2 text-xs text-gray-500">Setelah transfer, upload bukti pembayaran di bawah.</p></div><div id="qrisInfo" class="rounded-xl bg-gray-50 p-4 text-sm" hidden><p class="font-semibold text-gray-900">Scan QRIS</p><img class="mx-auto my-4 h-44 w-44 rounded-lg" src="https://quickchart.io/qr?text={{ urlencode($qrisMerchant.'|'.number_format($price, 0, '', '')) }}&size=220" alt="QRIS payment code"><p class="text-center text-xs text-gray-500">QRIS reference akan dibuat otomatis saat submit.</p></div><label id="proofField" class="block text-sm font-semibold text-gray-700">Bukti transfer<input name="proof" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" class="mt-2 block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm font-normal"></label><button class="w-full rounded-lg bg-emerald-700 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-800">Submit payment for review</button></form></section></div>
@if($payment)<section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
    <div class="flex flex-wrap items-center justify-between gap-3"><div>
        <p class="text-xs text-gray-500">Latest invoice</p>
        <h2 class="font-bold text-gray-900">{{ $payment->invoice_number }}</h2>
        <p class="mt-1 text-sm text-gray-500">{{ $payment->method === 'qris' ? 'QRIS' : 'Bank transfer' }} · Rp {{ number_format($payment->amount, 0, ',', '.') }}</p>
    </div><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $payment->status === 'approved' ? 'bg-emerald-50 text-emerald-700' : ($payment->status === 'rejected' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700') }}">{{ ucfirst($payment->status) }}</span>
</div>@if($payment->admin_note)
<p class="mt-4 rounded-lg bg-gray-50 p-3 text-sm text-gray-600">Admin note: {{ $payment->admin_note }}</p>
@endif</section>@endif
</div>
@endsection